spring.application.name=dev_help
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.open-in-view=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


logging.level.root=WARN
logging.level.org.springframework.security=WARN
logging.level.org.hibernate=WARN

spring.main.banner-mode=off

spring.security.user.name=${SECURITY_USER_NAME}
spring.security.user.password=${SECURITY_USER_PASSWORD}